OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1 # Số lượng Peer (peer0)
    Users:
      Count: 1 # Số lượng User admin phụ ngoài Admin mặc định